-- Yield Portal service login for Streamlit Cloud (Analytics account).
-- Run once in Snowsight as ACCOUNTADMIN. Key-pair login only: no password, no MFA prompt.
-- The private key never goes in this file; it lives in the app's Streamlit secrets.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS YIELD_PORTAL_ROLE
  COMMENT = 'Yield Portal app: read/write YIELD_REPORTS only';
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE YIELD_PORTAL_ROLE;
GRANT USAGE ON DATABASE YIELD_REPORTS TO ROLE YIELD_PORTAL_ROLE;
GRANT USAGE ON SCHEMA YIELD_REPORTS.PUBLIC TO ROLE YIELD_PORTAL_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE YIELD_REPORTS.PUBLIC.YIELD_OBSERVATIONS TO ROLE YIELD_PORTAL_ROLE;
-- imports stage rows in a temporary table first, which needs CREATE TABLE
GRANT CREATE TABLE ON SCHEMA YIELD_REPORTS.PUBLIC TO ROLE YIELD_PORTAL_ROLE;
GRANT ROLE YIELD_PORTAL_ROLE TO ROLE SYSADMIN;

CREATE USER IF NOT EXISTS YIELD_PORTAL_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = YIELD_PORTAL_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = YIELD_REPORTS.PUBLIC
  RSA_PUBLIC_KEY = '<public key body: one line, no BEGIN/END lines>'
  COMMENT = 'Yield Portal (Streamlit Cloud) - key-pair login only';
GRANT ROLE YIELD_PORTAL_ROLE TO USER YIELD_PORTAL_SVC;

-- Check: RSA_PUBLIC_KEY_FP must read <the key's SHA256 fingerprint>
DESC USER YIELD_PORTAL_SVC;
